version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: rtd/requirements.txt

sphinx:
  configuration: rtd/source/conf.py
  fail_on_warning: false
